// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type Query struct {
}

type Todo struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	Done      bool   `json:"done"`
	CreatedAt string `json:"createdAt"`
}

type UpdateTodo struct {
	Text *string `json:"text,omitempty"`
	Done *bool   `json:"done,omitempty"`
}
